### ISSUE TITLE
Resolve conflicting log implementations in Cloudflow

### ISSUE THREAD

**Issue by olofwalker** [lightbend/cloudflow#620]
The problem here is that several logging frameworks (Logback and log4j) are pulled in by Cloudflow, this is something we have to fix.

There are ways to work around this for users of the current versions., for example, add the following configuration to your Cloudflow application `build.sbt` file.

.settings(
    useCoursier := false,
    excludeDependencies += "org.slf4j" % "slf4j-log4j12",
    excludeDependencies += "log4j"     % "log4j",
)

We have to temporarily disable `Coursier` because of this issue:
https://github.com/coursier/coursier/issues/1590

**Comment by tringuyen-yw** [comment]
`log4j` is used by the local loggers (when testing the pipeline by `sbt runLocal`)

```
excludeDependencies += "org.slf4j" % "slf4j-log4j12",
excludeDependencies += "log4j" % "log4j"
```

will cause an exception when the streamlet loggers kick in:

```
/Users/abc/cloudflow/examples/snippets/modules/ROOT/examples/sensor-data-scala/src/main/blueprint/blueprint.conf verified.
[error] java.util.NoSuchElementException: None.get
[error]         at scala.None$.get(Option.scala:529)
[error]         at scala.None$.get(Option.scala:527)
[error]         at cloudflow.sbt.CloudflowLocalRunnerPlugin$.$anonfun$findLogLibsInPluginClasspath$2(CloudflowLocalRunnerPlugin.scala:183)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error]         at scala.collection.immutable.List.map(List.scala:298)
[error]         at cloudflow.sbt.CloudflowLocalRunnerPlugin$.findLogLibsInPluginClasspath(CloudflowLocalRunnerPlugin.scala:183)
[error]         at cloudflow.sbt.CloudflowLocalRunnerPlugin$.$anonfun$projectSettings$11(CloudflowLocalRunnerPlugin.scala:102)
[error]         at cloudflow.sbt.CloudflowLocalRunnerPlugin$.$anonfun$projectSettings$11$adapted(CloudflowLocalRunnerPlugin.scala:88)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (runLocal) java.util.NoSuchElementException: None.get
[error] Total time: 4 s, completed Aug. 6, 2020, 10:01:55 p.m.
```

**Comment by tringuyen-yw** [comment]
In case Cloudflow uses a single logging framework, can you use logback? Because this allows to configure `logback.xml` to inject [Mapped Diagnostic Context](http://logback.qos.ch/manual/mdc.html) info

**Comment by RayRoestenburg** [comment]
Fixed in https://github.com/lightbend/cloudflow/commit/58a9234cdd80f9995e8eac9babb9f695688bfdf2

**Comment by RayRoestenburg** [comment]
It still seems to be an issue in sensor-data-scala example. log4j and slsf4j-log4j are in classpath

**Comment by ennru** [comment]
With #692 `runLocal` operates in the `Test` scope and the log dependencies as scoped to that.
