### ISSUE TITLE
Map Config for streamlets

### ISSUE THREAD

**Issue by OBenner** [lightbend/cloudflow#941]
**Is your feature request related to a problem? Please describe.**
A way to use map-config in streamlet configuration

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**
I tryed with flink streamlet.

**Describe the solution you'd like**
`

> cloudflow {
>   streamlets {
>     flink {
>       config-parameters {
>        map-config =[
>           { task1 : 1 },
>           { task2 : 2 },
>           { task3 : 3 },
>           { task4 : 4 },
>           { task5 : 5 } ]
>       }
>     }
>   }
> }

`

**Additional context**
Not possible to get configuration settings with non-string representation.
Example  : https://github.com/OBenner/cloudflow-map-config
Usage  : runLocal 
Error : `Exception in thread "main" com.typesafe.config.ConfigException$WrongType: D:\OKB\cloudflow-map-config\flink-pipe\src\main\resources\local.conf: 14: cloudflow.streamlets.flink.config-parameters.map-config has type LIST rather than STRING
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:163)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:180)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:180)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:180)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:180)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:250)
	at cloudflow.localrunner.LocalRunner$.$anonfun$resolveLocalStreamletConf$1(LocalRunner.scala:207)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:273)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at cloudflow.localrunner.LocalRunner$.resolveLocalStreamletConf(LocalRunner.scala:201)
	at cloudflow.localrunner.LocalRunner$.$anonfun$run$3(LocalRunner.scala:114)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:273)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at cloudflow.localrunner.LocalRunner$.run(LocalRunner.scala:112)
	at cloudflow.localrunner.LocalRunner$.$anonfun$main$3(LocalRunner.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at cloudflow.localrunner.LocalRunner$.$anonfun$main$2(LocalRunner.scala:86)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at cloudflow.localrunner.LocalRunner$.main(LocalRunner.scala:86)
	at cloudflow.localrunner.LocalRunner.main(LocalRunner.scala)
`

**Comment by andreaTP** [comment]
Can replicate locally and proposed a fix for it, thanks for reporting @OBenner !

**Comment by andreaTP** [comment]
After investigation, I found that this configuration is not supported ATM in Cloudflow at the moment.

The comprehensive list of available config-parameter types is here @OBenner :
https://cloudflow.io/docs/current/develop/streamlet-configuration.html

A bad "workaround" is currently to encode your configuration in a quoted `String` and re-parse it.
